import { test, expect } from '@playwright/test';
import { createHash } from 'node:crypto';

test('Private score links and profile records disappear after sign-out', async ({ page }) => {
  const username = 'ir_browser_' + Date.now();
  const headers = { 'X-LazerRave': '1' };
  const registered = await page.request.post('/api/auth/register', { headers, data: { username, email: username + '@example.com', password: 'ir-browser-fixture-password' } });
  expect(registered.ok()).toBeTruthy(); const user = await registered.json();
  const title = 'Private browser chart ' + username;
  const file = Buffer.from('#TITLE ' + title);
  const response = await page.request.post('/api/charts/register', { headers, data: { sha256: createHash('sha256').update(file).digest('hex'), md5: createHash('md5').update(file).digest('hex'), title, artist: 'Fixture', difficulty: 'ANOTHER', keys: 7, level: 12, visibility: 'restricted' } });
  expect(response.ok()).toBeTruthy(); const chart = await response.json();
  const submitted = await page.request.post('/api/scores', { headers, data: { chartId: chart.chartId, boardId: chart.id, clientRunId: crypto.randomUUID(), ruleset: 'openlr2-v1', arrangement: 'off', gauge: 'normal', perfect: 10, great: 5, good: 3, bad: 2, poor: 1, maxCombo: 10, clear: 'normal', scoreMax: 50, normalScore: 12000 } });
  expect(submitted.ok()).toBeTruthy(); const score = await submitted.json();
  await page.goto('/scores/' + score.id);
  await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible();
  await expect(page.getByText('PGREAT', { exact: true })).toBeVisible();
  await page.goto('/players/id/' + user.uid);
  await expect(page.getByRole('heading', { name: 'Play records', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: title, exact: true }).last()).toBeVisible();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('navigation').getByRole('link', { name: 'Sign in', exact: true })).toBeVisible();
  await page.goto('/players/id/' + user.uid);
  await expect(page.getByRole('heading', { name: 'Play records', exact: true })).toBeVisible();
  await expect(page.getByText(title, { exact: true })).toHaveCount(0);
  await page.goto('/scores/' + score.id);
  await expect(page.getByRole('alert')).toContainText('Score not found.');
  await expect(page.getByText(title, { exact: true })).toHaveCount(0);
  await page.goto('/rankings/' + chart.id);
  await expect(page.getByRole('alert')).toContainText('Chart not found.');
  await expect(page.getByText(title, { exact: true })).toHaveCount(0);
});

test('Chart directory filters persist in URL and reload, including all key modes', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/rankings');
  await expect(page.getByLabel('Key mode', { exact: true })).toHaveValue('7');
  await page.getByLabel('Search charts', { exact: true }).fill('Fixture');
  await page.getByLabel('Key mode', { exact: true }).selectOption('5');
  await page.getByLabel('Minimum level', { exact: true }).fill('3');
  await page.getByLabel('Maximum level', { exact: true }).fill('12');
  await page.getByLabel('Sort by', { exact: true }).selectOption('plays');
  await page.getByLabel('Difficulty', { exact: true }).selectOption('ANOTHER');
  await expect(page).toHaveURL(/keys=5/);
  await page.reload();
  await expect(page.getByLabel('Sort by', { exact: true })).toHaveValue('plays');
  await expect(page.getByLabel('Difficulty', { exact: true })).toHaveValue('ANOTHER');
  await expect(page.getByLabel('Search charts', { exact: true })).toHaveValue('Fixture');
  await expect(page.getByLabel('Key mode', { exact: true })).toHaveValue('5');
  await expect(page.getByLabel('Minimum level', { exact: true })).toHaveValue('3');
  await expect(page.getByLabel('Maximum level', { exact: true })).toHaveValue('12');
  const request = page.waitForRequest(req => new URL(req.url()).pathname === '/api/charts' && !new URL(req.url()).searchParams.has('keys'));
  await page.getByLabel('Key mode', { exact: true }).selectOption('all'); await request;
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByLabel('Language', { exact: true }).selectOption('zh-CN');
  await expect(page.getByLabel('键型', { exact: true })).toHaveValue('all');
  expect(errors).toEqual([]);
});
