export interface User { id: string; uid: number; username: string; displayName: string; signature: string; bio: string; avatarUrl: string | null; role: 'player' | 'admin'; createdAt: string }
export interface Pack { id: string; title: string; description: string; sha256: string; sizeBytes: number; published?: boolean; createdAt: string }
export interface PackCatalogEntry extends Pack { chartCount: number; keys: number[]; minimumLevel: number; maximumLevel: number }
export interface PackCatalog { items: PackCatalogEntry[]; total: number; page: number; pageSize: number }
export interface SongGroup { songKey: string; title: string; artist: string; chartCount: number; keys: number[]; minimumLevel: number; maximumLevel: number; approved: boolean; playCount: number; playerCount: number; lastPlayedAt: string | null }
export interface SongDirectory { items: SongGroup[]; total: number; page: number; pageSize: number }
export interface SongDetail { key: string; title: string; artist: string; charts: Chart[] }
export interface Chart { songKey?: string; songTitle?: string; displayDifficulty?: string; id: string; chartId: string; title: string; artist: string; difficulty: string; keys: number; level: number; sha256: string; md5: string; packId: string | null; path?: string; visibility: 'public' | 'unlisted' | 'restricted' | 'hidden'; approved: boolean; ownerId: string | null; bpm: number | null; lengthMs: number | null; playCount?: number; playerCount?: number; lastPlayedAt?: string | null }
export interface Score { id: string; rank: number; position?: number; uid: number; username: string; displayName: string; avatarUrl?: string | null; exScore: number; scoreMax: number | null; normalScore: number | null; misses: number; minMisses: number; maxCombo: number; clear: string; bestClear: string; letterRank: string | null; perfect: number; great: number; good: number; bad: number; poor: number; arrangement: string; gauge: string; inputType: string; comment: string; verified: boolean; createdAt: string; playedAt?: string | null; playCount?: number; chartId?: string; title?: string; keys?: number; level?: number; visibility?: string; replayAvailable?: boolean; ruleset?: string }
export interface RankingSummary { submissions: number; players: number; clearedPlayers: number; failed: number; assist: number; easy: number; normal: number; hard: number; fullCombo: number; perfect: number }
