X(1, BARGRAPHOP_SONGPROGRESS)\
X(2, BARGRAPHOP_SONGLOADED)\
\
X(3, BARGRAPHOP_LEVEL_BAR)\
\
X(5, BARGRAPHOP_SAMEFOLDER_BEGINNER_LEVEL)\
X(6, BARGRAPHOP_SAMEFOLDER_NORMAL_LEVEL)\
X(7, BARGRAPHOP_SAMEFOLDER_HYPER_LEVEL)\
X(8, BARGRAPHOP_SAMEFOLDER_ANOTHERL_LEVEL)\
X(9, BARGRAPHOP_SAMEFOLDER_INSANE_LEVEL)\
\
X(10, BARGRAPHOP_1P_EXSCORE_NOW)\
X(11, BARGRAPHOP_1P_EXSCORE_PREDICT)\
X(12, BARGRAPHOP_1P_HIGHSCORE_NOW)\
X(13, BARGRAPHOP_1P_HIGHSCORE_PREDICT)\
X(14, BARGRAPHOP_2P_TARGET_EXSCORE_NOW)\
X(15, BARGRAPHOP_2P_TARGET_EXSCORE_PREDICT)\
\
X(20, BARGRAPHOP_1P_PG_TOTALNOTES)\
X(21, BARGRAPHOP_1P_GR_TOTALNOTES)\
X(22, BARGRAPHOP_1P_GD_TOTALNOTES)\
X(23, BARGRAPHOP_1P_BD_TOTALNOTES)\
X(24, BARGRAPHOP_1P_PR_TOTALNOTES)\
X(25, BARGRAPHOP_1P_MAXCOMBO_TOTALNOTES)\
X(26, BARGRAPHOP_1P_SCORE_200000)\
X(27, BARGRAPHOP_1P_EXSCORE_TOTALNOTES__2)\
\
\
X(30, BARGRAPHOP_2P_TARGET_PG_TOTALNOTES)\
X(31, BARGRAPHOP_2P_TARGET_GR_TOTALNOTES)\
X(32, BARGRAPHOP_2P_TARGET_GD_TOTALNOTES)\
X(33, BARGRAPHOP_2P_TARGET_BD_TOTALNOTES)\
X(34, BARGRAPHOP_2P_TARGET_PR_TOTALNOTES)\
X(35, BARGRAPHOP_2P_TARGET_MAXCOMBO_TOTALNOTES)\
X(36, BARGRAPHOP_2P_TARGET_SCORE_200000)\
X(37, BARGRAPHOP_2P_TARGET_EXSCORE_TOTALNOTES__2)\
\
X(40, BARGRAPHOP_HIGHSCORE_PG_TOTALNOTES)\
X(41, BARGRAPHOP_HIGHSCORE_GR_TOTALNOTES)\
X(42, BARGRAPHOP_HIGHSCORE_GD_TOTALNOTES)\
X(43, BARGRAPHOP_HIGHSCORE_BD_TOTALNOTES)\
X(44, BARGRAPHOP_HIGHSCORE_PR_TOTALNOTES)\
X(45, BARGRAPHOP_HIGHSCORE_MAXCOMBO_TOTALNOTES)\
X(46, BARGRAPHOP_HIGHSCORE_SCORE_200000)\
X(47, BARGRAPHOP_HIGHSCORE_EXSCORE_TOTALNOTES__2)\
\
X(48, BARGRAPHOP_1P_RATIO_SLOW)\
X(49, BARGRAPHOP_1P_RATIO_FAST)\
X(58, BARGRAPHOP_2P_RATIO_SLOW)\
X(59, BARGRAPHOP_2P_RATIO_SLOW)\
