X(10, NUMBEROP_HS_1P)\
X(11, NUMBEROP_HS_2P)\
\
X(12, NUMBEROP_JUDGE_TIMING)\
X(13, NUMBEROP_DEFAULT_TARGET_RATE)\
\
X(14, NUMBEROP_SUD_1P)\
X(15, NUMBEROP_SUD_2P)\
\
\
X(20, NUMBEROP_FPS)\
X(21, NUMBEROP_YEAR)\
X(22, NUMBEROP_MONTH)\
X(23, NUMBEROP_DAY)\
X(24, NUMBEROP_HOUR)\
X(25, NUMBEROP_MINUTE)\
X(26, NUMBEROP_SECOND)\
\
\
X(30, NUMBEROP_TOTAL_PLAY_COUNT)\
X(31, NUMBEROP_TOTAL_CLEAR_COUNT)\
X(32, NUMBEROP_TOTAL_FAIL_COUNT)\
\
X(33, NUMBEROP_TOTAL_PERFECT)\
X(34, NUMBEROP_TOTAL_GREAT)\
X(35, NUMBEROP_TOTAL_GOOD)\
X(36, NUMBEROP_TOTAL_BAD)\
X(37, NUMBEROP_TOTAL_POOR)\
\
X(38, NUMBEROP_RUNNING_COMBO)\
X(39, NUMBEROP_RUNNING_MAXCOMBO)\
\
X(40, NUMBEROP_TRIAL_LEVEL)\
X(41, NUMBEROP_TRIAL_LEVEL_OLD)\
\
\
X(45, NUMBEROP_BEGINNERSONGLEVEL)\
X(46, NUMBEROP_NORMALSONGLEVEL)\
X(47, NUMBEROP_HYPERSONGLEVEL)\
X(48, NUMBEROP_ANOTHERSONGLEVEL)\
X(49, NUMBEROP_INSANESONGLEVEL)\
\
X(50, NUMBEROP_EQ0)\
X(51, NUMBEROP_EQ1)\
X(52, NUMBEROP_EQ2)\
X(53, NUMBEROP_EQ3)\
X(54, NUMBEROP_EQ4)\
X(55, NUMBEROP_EQ5)\
X(56, NUMBEROP_EQ6)\
\
X(57, NUMBEROP_MASTER_VOLUME)\
X(58, NUMBEROP_KEY_VOLUME)\
X(59, NUMBEROP_BGM_VOLUME)\
\
X(60, NUMBEROP_FX0_P1)\
X(61, NUMBEROP_FX0_P2)\
X(62, NUMBEROP_FX1_P1)\
X(63, NUMBEROP_FX1_P2)\
X(64, NUMBEROP_FX2_P1)\
X(65, NUMBEROP_FX2_P2)\
\
X(66, NUMBEROP_PITCH)\
\
X(70, NUMBEROP_SCORE)\
X(71, NUMBEROP_EXSCORE)\
X(72, NUMBEROP_EXSCOREMAX)\
X(73, NUMBEROP_RATE)\
X(74, NUMBEROP_TOTALNOTES)\
X(75, NUMBEROP_MAXCOMBO)\
X(76, NUMBEROP_MIN_BP)\
X(77, NUMBEROP_PLAYCOUNT)\
X(78, NUMBEROP_CLEAR)\
X(79, NUMBEROP_FAIL)\
\
X(80, NUMBEROP_PERFECT)\
X(81, NUMBEROP_GREAT)\
X(82, NUMBEROP_GOOD)\
X(83, NUMBEROP_BAD)\
X(84, NUMBEROP_POOR)\
X(85, NUMBEROP_PERFECT_PERCENT)\
X(86, NUMBEROP_GREAT_PERCENT)\
X(87, NUMBEROP_GOOD_PERCENT)\
X(88, NUMBEROP_BAD_PERCENT)\
X(89, NUMBEROP_POOR_PERCENT)\
\
X(90, NUMBEROP_BPM_MAX)\
X(91, NUMBEROP_BPM_MIN)\
\
X(92, NUMBEROP_IR_RANK)\
X(93, NUMBEROP_IR_TOTALPLAYER)\
X(94, NUMBEROP_IR_CLEARRATE)\
\
X(95, NUMBEROP_IR_DIFFRIVAL)\
\
\
X(100, NUMBEROP_SCORE)\
X(101, NUMBEROP_EXSCORE)\
X(102, NUMBEROP_RATE)\
X(103, NUMBEROP_RATE_POINT)\
X(104, NUMBEROP_NOWCOMBO)\
X(105, NUMBEROP_MAXCOMBO)\
X(106, NUMBEROP_TOTALNOTES)\
X(107, NUMBEROP_GROOVEGAUGE)\
X(108, NUMBEROP_DIFFEXSCORE2P)\
X(110, NUMBEROP_PERFECT)\
X(111, NUMBEROP_GREAT)\
X(112, NUMBEROP_GOOD)\
X(113, NUMBEROP_BAD)\
X(114, NUMBEROP_POOR)\
X(115, NUMBEROP_TOTAL_RATE)\
X(116, NUMBEROP_TOTAL_RATE_POINT)\
\
\
X(120, NUMBEROP_OPPONENT_SCORE)\
X(121, NUMBEROP_OPPONENT_EXSCORE)\
X(122, NUMBEROP_OPPONENT_RATE)\
X(123, NUMBEROP_OPPONENT_RATE_POINT)\
X(124, NUMBEROP_OPPONENT_NOWCOMBO)\
X(125, NUMBEROP_OPPONENT_MAXCOMBO)\
X(126, NUMBEROP_OPPONENT_TOTALNOTES)\
X(127, NUMBEROP_OPPONENT_GROOVEGAUGE)\
X(128, NUMBEROP_OPPONENT_DIFFEXSCORE2P)\
X(130, NUMBEROP_OPPONENT_PERFECT)\
X(131, NUMBEROP_OPPONENT_GREAT)\
X(132, NUMBEROP_OPPONENT_GOOD)\
X(133, NUMBEROP_OPPONENT_BAD)\
X(134, NUMBEROP_OPPONENT_POOR)\
X(135, NUMBEROP_OPPONENT_TOTAL_RATE)\
X(136, NUMBEROP_OPPONENT_TOTAL_RATE_POINT)\
\
\
X(150, NUMBEROP_CURRENT_HIGHSCORE)\
X(151, NUMBEROP_TARGETSCORE)\
X(152, NUMBEROP_DIFF_HIGHSCORE_1P)\
X(153, NUMBEROP_DIFF_TARGET_1P)\
X(154, NUMBEROP_DIFFNEXTRANK)\
X(155, NUMBEROP_HIGHSCORE_RATE)\
X(156, NUMBEROP_HIGHSCORE_RATEPOINT)\
X(157, NUMBEROP_TARGET_RATE)\
X(158, NUMBEROP_TARGET_RATEPOINT)\
\
\
X(160, NUMBEROP_BPM)\
X(161, NUMBEROP_MINUTE)\
X(162, NUMBEROP_SECOND)\
X(163, NUMBEROP_LEFT_MINUTE)\
X(164, NUMBEROP_LEFT_SECOND)\
X(165, NUMBEROP_LOADPERCENTAGE)\
\
\
X(170, NUMBEROP_OLDEXSCORE)\
X(171, NUMBEROP_NEWEXSCORE)\
X(172, NUMBEROP_DIFFEXSCORE)\
\
X(173, NUMBEROP_OLDMAXCOMBO)\
X(174, NUMBEROP_NEWMAXCOMBO)\
X(175, NUMBEROP_DIFFMAXCOMBO)\
\
X(176, NUMBEROP_OLDBP)\
X(177, NUMBEROP_NEWBP)\
X(178, NUMBEROP_DIFFBP)\
\
X(179, NUMBEROP_IR_RANK)\
X(180, NUMBEROP_IR_TOTALPLAYER)\
X(181, NUMBEROP_IR_CLEARRATE)\
X(182, NUMBEROP_OLD_IRRANK)\
\
X(183, NUMBEROP_OLD_RATE)\
X(184, NUMBEROP_OLD_RATEPOINT)\
\
\
X(200, NUMBEROP_IR_TOTALPLAYER)\
X(201, NUMBEROP_IR_TOTALPLAYCOUNT/1PHITOFFSET)\
\
X(210, NUMBEROP_FAILED_PLAYER/1PFASTSLOW)\
X(211, NUMBEROP_FAILED_RATE/2PFASTSLOW)\
X(212, NUMBEROP_EASY_PLAYER/FASTCOUNT)\
X(213, NUMBEROP_EASY_RATE/2PHITOFFSET)\
X(214, NUMBEROP_CLEAR_PLAYER/SLOWCOUNT)\
X(215, NUMBEROP_CLEAR_RATE)\
X(216, NUMBEROP_HARD_PLAYER/COMBOBREAKS)\
X(217, NUMBEROP_HARD_RATE/REMAINNOTES)\
X(218, NUMBEROP_FULLCOMBO_PLAYER/CURRENTNOTE)\
X(219, NUMBEROP_FULLCOMBO_RATE)\
\
X(220, NUMBEROP_REMAINIRAUTOUPDATETIME)\
\
X(250, NUMBEROP_COURSELEVELSTAGE1)\
X(251, NUMBEROP_COURSELEVELSTAGE2)\
X(252, NUMBEROP_COURSELEVELSTAGE3)\
X(253, NUMBEROP_COURSELEVELSTAGE4)\
X(254, NUMBEROP_COURSELEVELSTAGE5)\
\
\
X(270, NUMBEROP_RIVAL_SCORE)\
X(271, NUMBEROP_RIVAL_EXSCORE)\
X(272, NUMBEROP_RIVAL_EXSCOREMAX)\
X(273, NUMBEROP_RIVAL_RATE)\
X(274, NUMBEROP_RIVAL_TOTALNOTES)\
X(275, NUMBEROP_RIVAL_MAXCOMBO)\
X(276, NUMBEROP_RIVAL_MIN_BP)\
X(277, NUMBEROP_RIVAL_PLAYCOUNT)\
X(278, NUMBEROP_RIVAL_CLEAR)\
X(279, NUMBEROP_RIVAL_FAIL)\
\
X(280, NUMBEROP_RIVAL_PERFECT)\
X(281, NUMBEROP_RIVAL_GREAT)\
X(282, NUMBEROP_RIVAL_GOOD)\
X(283, NUMBEROP_RIVAL_BAD)\
X(284, NUMBEROP_RIVAL_POOR)\
X(285, NUMBEROP_RIVAL_PERFECT_PERCENT)\
X(286, NUMBEROP_RIVAL_GREAT_PERCENT)\
X(287, NUMBEROP_RIVAL_GOOD_PERCENT)\
X(288, NUMBEROP_RIVAL_BAD_PERCENT)\
X(289, NUMBEROP_RIVAL_POOR_PERCENT)\
\
X(290, NUMBEROP_RIVAL_BPM_MAX)\
X(291, NUMBEROP_RIVAL_BPM_MIN)\
\
X(292, NUMBEROP_RIVAL_IR_RANK)\
X(293, NUMBEROP_RIVAL_IR_TOTALPLAYER)\
X(294, NUMBEROP_RIVAL_IR_CLEARRATE)\
\
X(295, NUMBEROP_1PRANDOMPATTERN)\
\
X(418, NUMBEROP_2PRANDOMPATTERN)\
\
X(421, NUMBEROP_LIFT_1P)\
X(422, NUMBEROP_LIFT_2P)\
\
