X(1, SLIDEROP_SONGSELECTPOSITION)\
\
X(2, SLIDEROP_HISPEED1P)\
X(3, SLIDEROP_HISPEED2P)\
\
X(4, SLIDEROP_SHUTTER1P)\
X(5, SLIDEROP_SHUTTER2P)\
\
X(6, SLIDEROP_SONGTIME)\
\
X(7, SLIDEROP_SKINCUSTOMSCROLL)\
\
X(8, SLIDEROP_IR_SCROLL_BAR)\
\
X(10, SLIDEROP_EQ0)\
X(11, SLIDEROP_EQ1)\
X(12, SLIDEROP_EQ2)\
X(13, SLIDEROP_EQ3)\
X(14, SLIDEROP_EQ4)\
X(15, SLIDEROP_EQ5)\
X(16, SLIDEROP_EQ6)\
\
X(17, SLIDEROP_MASTER_VOLUME)\
X(18, SLIDEROP_KEY_VOLUME)\
X(19, SLIDEROP_BGM_VOLUME)\
\
X(20, SLIDEROP_MASTER_FX_P1)\
X(21, SLIDEROP_MASTER_FX_P2)\
X(22, SLIDEROP_KEY_FX_P1)\
X(23, SLIDEROP_KEY_FX_P2)\
X(24, SLIDEROP_BGM_FX_P1)\
X(25, SLIDEROP_BGM_FX_P2)\
\
X(26, SLIDEROP_PITCH)\
\
X(27, SLIDEROP_LIFT1P)\
X(28, SLIDEROP_LIFT2P)\
