X(1, TEXTOP_TARGETNAME)\
X(2, TEXTOP_MYNAME)\
\
X(10, TEXTOP_THISSONG_TITLE)\
X(11, TEXTOP_THISSONG_SUBTITLE)\
X(12, TEXTOP_THISSONG_FULLTITLE)\
X(13, TEXTOP_THISSONG_GENRE)\
X(14, TEXTOP_THISSONG_ARTIST)\
X(15, TEXTOP_THISSONG_SUBARTIST)\
X(16, TEXTOP_THISSONG_SEARCHTAG)\
X(17, TEXTOP_THISSONG_PLAYLEVEL)\
X(18, TEXTOP_THISSONG_DIFFICULTYCOUNT)\
\
\
X(20, TEXTOP_TAGEDIT_TITLE)\
X(21, TEXTOP_TAGEDIT_SUBTITLE)\
X(22, TEXTOP_TAGEDIT_FULLTITLE)\
X(23, TEXTOP_TAGEDIT_GENRE)\
X(24, TEXTOP_TAGEDIT_ARTIST)\
X(25, TEXTOP_TAGEDIT_SUBARTIST)\
X(26, TEXTOP_TAGEDIT_SEARCHTAG)\
X(27, TEXTOP_TAGEDIT_PLAYLEVEL)\
X(28, TEXTOP_TAGEDIT_DIFFICULTYCOUNT)\
X(29, TEXTOP_TAGEDIT_EXLEVEL)\
X(30, TEXTOP_SEARCH_COMMAND_JUKEBOXNAME)\
\
\
X(40, TEXTOP_SLOT0)\
X(41, TEXTOP_SLOT1)\
X(42, TEXTOP_SLOT2)\
X(43, TEXTOP_SLOT3)\
X(44, TEXTOP_SLOT4)\
X(45, TEXTOP_SLOT5)\
X(46, TEXTOP_SLOT6)\
X(47, TEXTOP_SLOT7)\
\
\
X(50, TEXTOP_SKIN_NAME)\
X(51, TEXTOP_SKIN_ARTIST)\
\
\
X(60, TEXTOP_PLAYMODE_KEY)\
X(61, TEXTOP_PLAYMODE_SORT)\
X(62, TEXTOP_PLAYMODE_DIFFICULTY)\
\
\
X(63, TEXTOP_RANDOM1P)\
X(64, TEXTOP_RANDOM2P)\
X(65, TEXTOP_GAUGE1P)\
X(66, TEXTOP_GAUGEP)\
X(67, TEXTOP_ASSIST1P)\
X(68, TEXTOP_ASSIST2P)\
X(69, TEXTOP_BATTLE)\
X(70, TEXTOP_FLIP)\
X(71, TEXTOP_SCOREGRAPH)\
X(72, TEXTOP_GHOST)\
X(73, TEXTOP_SHUTTER)\
X(74, TEXTOP_SCROLLTYPE)\
\
X(75, TEXTOP_BGA_SIZE)\
X(76, TEXTOP_BGA_DRAW)\
\
X(77, TEXTOP_SCREENCOLORS)\
X(78, TEXTOP_VSYNC)\
X(79, TEXTOP_SCREENMODE)\
\
X(80, TEXTOP_AUTOJUDGE)\
X(81, TEXTOP_REPLAYOPTION)\
\
X(82, TEXTOP_TRIAL1)\
X(83, TEXTOP_TRIAL2)\
\
X(84, TEXTOP_EFFECT1P)\
X(85, TEXTOP_EFFECT2P)\
\
\
\
X(100, TEXTOP_SKINCUSTOMIZE_CATEGORY1)\
X(101, TEXTOP_SKINCUSTOMIZE_CATEGORY2)\
X(102, TEXTOP_SKINCUSTOMIZE_CATEGORY3)\
X(103, TEXTOP_SKINCUSTOMIZE_CATEGORY4)\
X(104, TEXTOP_SKINCUSTOMIZE_CATEGORY5)\
X(105, TEXTOP_SKINCUSTOMIZE_CATEGORY6)\
X(106, TEXTOP_SKINCUSTOMIZE_CATEGORY7)\
X(107, TEXTOP_SKINCUSTOMIZE_CATEGORY8)\
X(108, TEXTOP_SKINCUSTOMIZE_CATEGORY9)\
X(109, TEXTOP_SKINCUSTOMIZE_CATEGORY10)\
\
X(110, TEXTOP_SKINCUSTOMIZE_ITEM1)\
X(111, TEXTOP_SKINCUSTOMIZE_ITEM2)\
X(112, TEXTOP_SKINCUSTOMIZE_ITEM3)\
X(113, TEXTOP_SKINCUSTOMIZE_ITEM4)\
X(114, TEXTOP_SKINCUSTOMIZE_ITEM5)\
X(115, TEXTOP_SKINCUSTOMIZE_ITEM6)\
X(116, TEXTOP_SKINCUSTOMIZE_ITEM7)\
X(117, TEXTOP_SKINCUSTOMIZE_ITEM8)\
X(118, TEXTOP_SKINCUSTOMIZE_ITEM9)\
X(119, TEXTOP_SKINCUSTOMIZE_ITEM10)\
\
X(120, TEXTOP_RANKING_PLAYERNAME1)\
X(121, TEXTOP_RANKING_PLAYERNAME2)\
X(122, TEXTOP_RANKING_PLAYERNAME3)\
X(123, TEXTOP_RANKING_PLAYERNAME4)\
X(124, TEXTOP_RANKING_PLAYERNAME5)\
X(125, TEXTOP_RANKING_PLAYERNAME6)\
X(126, TEXTOP_RANKING_PLAYERNAME7)\
X(127, TEXTOP_RANKING_PLAYERNAME8)\
X(128, TEXTOP_RANKING_PLAYERNAME9)\
X(129, TEXTOP_RANKING_PLAYERNAME10)\
\
X(130, TEXTOP_CLEARTEXT_TEMP1)\
X(131, TEXTOP_CLEARTEXT_TEMP2)\
\
\
X(150, TEXTOP_COURSETITLE_1STAGE)\
X(151, TEXTOP_COURSETITLE_2STAGE)\
X(152, TEXTOP_COURSETITLE_3STAGE)\
X(153, TEXTOP_COURSETITLE_4STAGE)\
X(154, TEXTOP_COURSETITLE_5STAGE)\
X(155, TEXTOP_COURSETITLE_6STAGE)\
X(156, TEXTOP_COURSETITLE_7STAGE)\
X(157, TEXTOP_COURSETITLE_8STAGE)\
X(158, TEXTOP_COURSETITLE_9STAGE)\
X(159, TEXTOP_COURSETITLE_10STAGE)\
\
X(160, TEXTOP_COURSESUBTITLE_1STAGE)\
X(161, TEXTOP_COURSESUBTITLE_2STAGE)\
X(162, TEXTOP_COURSESUBTITLE_3STAGE)\
X(163, TEXTOP_COURSESUBTITLE_4STAGE)\
X(164, TEXTOP_COURSESUBTITLE_5STAGE)\
X(165, TEXTOP_COURSESUBTITLE_6STAGE)\
X(166, TEXTOP_COURSESUBTITLE_7STAGE)\
X(167, TEXTOP_COURSESUBTITLE_8STAGE)\
X(168, TEXTOP_COURSESUBTITLE_9STAGE)\
X(169, TEXTOP_COURSESUBTITLE_10STAGE)\
\
X(170, TEXTOP_COURSEEDITANDNAME)\
\
X(171, TEXTOP_COURSECONNECTIONSTAGE1-2)\
X(172, TEXTOP_COURSECONNECTIONSTAGE2-3)\
X(173, TEXTOP_COURSECONNECTIONSTAGE3-4)\
X(174, TEXTOP_COURSECONNECTIONSTAGE4-5)\
X(175, TEXTOP_COURSECONNECTIONSTAGE5-6)\
X(176, TEXTOP_COURSECONNECTIONSTAGE6-7)\
X(177, TEXTOP_COURSECONNECTIONSTAGE7-8)\
X(178, TEXTOP_COURSECONNECTIONSTAGE8-9)\
X(179, TEXTOP_COURSECONNECTIONSTAGE9-10)\
\
\
X(180, TEXTOP_COURSEOPTION_SOFLAN)\
X(181, TEXTOP_COURSEOPTION_GAUGETYPE)\
X(182, TEXTOP_COURSEOPTION_OPTIONBAN)\
X(183, TEXTOP_COURSEOPTION_IR)\
\
\
X(190, TEXTOP_RANDOMCOURSEOPTIONLEVELFORME)\
X(191, TEXTOP_RANDOMCOURSEOPTIONLEVELMAX)\
X(192, TEXTOP_RANDOMCOURSEOPTIONLEVELMIN)\
X(193, TEXTOP_RANDOMCOURSEOPTIONBPMRANGE)\
X(194, TEXTOP_RANDOMCOURSEOPTIONBPMMAX)\
X(195, TEXTOP_RANDOMCOURSEOPTIONBPMMIN)\
X(196, TEXTOP_RANDOMCOURSEOPTIONSTAGES)\
\
\
X(198, TEXTOP_ALLCOURSEOPTIONDEFAULTCONNECTION)\
X(199, TEXTOP_ALLCOURSEOPTIONDEFAULTGAUGE)\
\
\
X(300, TEXTOP_SCALINGFILTER)\
X(301, TEXTOP_STRETCH)\
X(302, TEXTOP_LIFT_ONOFF)\
\
